# Generated by Django 5.2.4 on 2025-09-09 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_alter_userprofile_options_userprofile_created_at_and_more'),
    ]

    operations = [
    ]
